name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASS }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Build Docker Image
        run: docker buildx build --file Dockerfile --tag doronch14/final-python:${{ github.run_number }}-${{ github.sha }} .

      - name: Push Docker Image to Docker Hub
        run: docker push doronch14/final-python:${{ github.run_number }}-${{ github.sha }}
  
